2020-11-25 13:01:18,430--test_login.py--48--ERROR--hanjiping_log--用例登录成功出现错误，错误信息为：0 != 2 within 7 places (2 difference)
2020-11-25 13:01:18,431--test_login.py--49--ERROR--hanjiping_log--0 != 2 within 7 places (2 difference)
Traceback (most recent call last):
  File "/Users/hanjiping/PycharmProjects/Port_test01/TestCase/test_login.py", line 44, in test_login
    self.assertAlmostEqual(expected['code'],res["code"])
  File "/opt/anaconda3/lib/python3.7/unittest/case.py", line 906, in assertAlmostEqual
    raise self.failureException(msg)
AssertionError: 0 != 2 within 7 places (2 difference)
2020-11-25 13:01:18,951--test_login.py--52--INFO--hanjiping_log--用例运行正常密码错误
2020-11-25 13:01:19,045--test_login.py--52--INFO--hanjiping_log--用例运行正常账号不是标准的手机号
2020-11-25 13:01:19,576--test_register.py--54--INFO--hanjiping_log--注册成功-带注册名该条用例通过
2020-11-25 13:01:20,226--test_register.py--54--INFO--hanjiping_log--成功-不带用户名该条用例通过
2020-11-25 13:01:20,375--test_register.py--54--INFO--hanjiping_log--不输入手机号该条用例通过
2020-11-25 13:01:20,500--test_register.py--54--INFO--hanjiping_log--手机号长度10位该条用例通过
2020-11-25 13:01:20,595--test_register.py--54--INFO--hanjiping_log--手机号长度12位该条用例通过
2020-11-25 13:01:20,688--test_register.py--54--INFO--hanjiping_log--手机号含有非法字符该条用例通过
2020-11-25 13:01:21,034--test_register.py--54--INFO--hanjiping_log--已注册过的手机号该条用例通过
2020-11-25 13:01:21,325--test_register.py--54--INFO--hanjiping_log--密码7位该条用例通过
2020-11-25 13:01:21,652--test_register.py--54--INFO--hanjiping_log--密码17位该条用例通过
2020-11-25 13:01:22,130--test_register.py--54--INFO--hanjiping_log--不输入密码该条用例通过
2020-11-25 13:01:22,664--test_register.py--50--ERROR--hanjiping_log--注册名11位该条测试用例未通过
2020-11-25 13:01:22,665--test_register.py--51--ERROR--hanjiping_log--2 != 0 within 7 places (2 difference)
Traceback (most recent call last):
  File "/Users/hanjiping/PycharmProjects/Port_test01/TestCase/test_register.py", line 48, in test_register
    self.assertAlmostEqual(expected['code'],res['code'])
  File "/opt/anaconda3/lib/python3.7/unittest/case.py", line 906, in assertAlmostEqual
    raise self.failureException(msg)
AssertionError: 2 != 0 within 7 places (2 difference)
