2020-11-28 22:46:22,305--test_login.py--48--ERROR--hanjiping_log--用例登录成功出现错误，错误信息为：0 != 2 within 7 places (2 difference)
2020-11-28 22:46:22,309--test_login.py--49--ERROR--hanjiping_log--0 != 2 within 7 places (2 difference)
Traceback (most recent call last):
  File "/Users/hanjiping/PycharmProjects/Port_test01/TestCase/test_login.py", line 44, in test_login
    self.assertAlmostEqual(expected['code'],res["code"])
  File "/opt/anaconda3/lib/python3.7/unittest/case.py", line 906, in assertAlmostEqual
    raise self.failureException(msg)
AssertionError: 0 != 2 within 7 places (2 difference)
2020-11-28 22:46:22,893--test_login.py--52--INFO--hanjiping_log--用例运行正常密码错误
2020-11-28 22:46:23,220--test_login.py--52--INFO--hanjiping_log--用例运行正常账号不是标准的手机号
2020-11-28 22:46:26,424--test_login.py--48--ERROR--hanjiping_log--用例登录成功出现错误，错误信息为：0 != 2 within 7 places (2 difference)
2020-11-28 22:46:26,424--test_login.py--49--ERROR--hanjiping_log--0 != 2 within 7 places (2 difference)
Traceback (most recent call last):
  File "/Users/hanjiping/PycharmProjects/Port_test01/TestCase/test_login.py", line 44, in test_login
    self.assertAlmostEqual(expected['code'],res["code"])
  File "/opt/anaconda3/lib/python3.7/unittest/case.py", line 906, in assertAlmostEqual
    raise self.failureException(msg)
AssertionError: 0 != 2 within 7 places (2 difference)
2020-11-28 22:46:26,763--test_login.py--52--INFO--hanjiping_log--用例运行正常密码错误
2020-11-28 22:46:27,103--test_login.py--52--INFO--hanjiping_log--用例运行正常账号不是标准的手机号
2020-11-28 22:46:27,954--test_register.py--56--INFO--hanjiping_log--注册成功-带注册名该条用例通过
