2020-11-28 22:52:32,770--test_login.py--48--ERROR--hanjiping_log--用例登录成功出现错误，错误信息为：0 != 2 within 7 places (2 difference)
2020-11-28 22:52:32,772--test_login.py--49--ERROR--hanjiping_log--0 != 2 within 7 places (2 difference)
Traceback (most recent call last):
  File "/Users/hanjiping/PycharmProjects/Port_test01/TestCase/test_login.py", line 44, in test_login
    self.assertAlmostEqual(expected['code'],res["code"])
  File "/opt/anaconda3/lib/python3.7/unittest/case.py", line 906, in assertAlmostEqual
    raise self.failureException(msg)
AssertionError: 0 != 2 within 7 places (2 difference)
2020-11-28 22:52:33,096--test_login.py--52--INFO--hanjiping_log--用例运行正常密码错误
2020-11-28 22:52:33,196--test_login.py--52--INFO--hanjiping_log--用例运行正常账号不是标准的手机号
2020-11-28 22:52:34,401--test_register.py--66--INFO--hanjiping_log--不输入手机号该条用例通过
2020-11-28 22:52:34,498--test_register.py--66--INFO--hanjiping_log--手机号长度10位该条用例通过
2020-11-28 22:52:34,598--test_register.py--66--INFO--hanjiping_log--手机号长度12位该条用例通过
2020-11-28 22:52:34,698--test_register.py--66--INFO--hanjiping_log--手机号含有非法字符该条用例通过
2020-11-28 22:52:35,039--test_register.py--66--INFO--hanjiping_log--已注册过的手机号该条用例通过
2020-11-28 22:52:35,647--test_register.py--66--INFO--hanjiping_log--密码7位该条用例通过
2020-11-28 22:52:36,055--test_register.py--66--INFO--hanjiping_log--密码17位该条用例通过
2020-11-28 22:52:36,417--test_register.py--66--INFO--hanjiping_log--不输入密码该条用例通过
2020-11-28 22:52:36,986--test_register.py--62--ERROR--hanjiping_log--注册名11位该条测试用例未通过
2020-11-28 22:52:36,987--test_register.py--63--ERROR--hanjiping_log--2 != 0 within 7 places (2 difference)
Traceback (most recent call last):
  File "/Users/hanjiping/PycharmProjects/Port_test01/TestCase/test_register.py", line 49, in test_register
    self.assertAlmostEqual(expected['code'],res['code'])
  File "/opt/anaconda3/lib/python3.7/unittest/case.py", line 906, in assertAlmostEqual
    raise self.failureException(msg)
AssertionError: 2 != 0 within 7 places (2 difference)
