2020-11-28 22:46:28,577--test_register.py--56--INFO--hanjiping_log--成功-不带用户名该条用例通过
2020-11-28 22:46:28,673--test_register.py--56--INFO--hanjiping_log--不输入手机号该条用例通过
2020-11-28 22:46:28,771--test_register.py--56--INFO--hanjiping_log--手机号长度10位该条用例通过
2020-11-28 22:46:28,869--test_register.py--56--INFO--hanjiping_log--手机号长度12位该条用例通过
2020-11-28 22:46:28,972--test_register.py--56--INFO--hanjiping_log--手机号含有非法字符该条用例通过
2020-11-28 22:46:29,364--test_register.py--56--INFO--hanjiping_log--已注册过的手机号该条用例通过
2020-11-28 22:46:29,698--test_register.py--56--INFO--hanjiping_log--密码7位该条用例通过
2020-11-28 22:46:30,070--test_register.py--56--INFO--hanjiping_log--密码17位该条用例通过
2020-11-28 22:46:30,483--test_register.py--56--INFO--hanjiping_log--不输入密码该条用例通过
2020-11-28 22:46:31,102--test_register.py--52--ERROR--hanjiping_log--注册名11位该条测试用例未通过
2020-11-28 22:46:31,102--test_register.py--53--ERROR--hanjiping_log--2 != 0 within 7 places (2 difference)
Traceback (most recent call last):
  File "/Users/hanjiping/PycharmProjects/Port_test01/TestCase/test_register.py", line 49, in test_register
    self.assertAlmostEqual(expected['code'],res['code'])
  File "/opt/anaconda3/lib/python3.7/unittest/case.py", line 906, in assertAlmostEqual
    raise self.failureException(msg)
AssertionError: 2 != 0 within 7 places (2 difference)
2020-11-28 22:46:32,457--test_register.py--56--INFO--hanjiping_log--类型输入非0，1内容该条用例通过
